server:
  port: 8020
spring:
  application:
    name: Ribbon-Consumer
#providers这个是自己命名的，ribbon,listOfServer这两个是规定的
#providers:
#  ribbon:
#    listOfServers: localhost:8010,localhost:8011

eureka:
#客户端
  client:
#注册中心地址
    service-url:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/
